workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          # This is optional - only needed if you have code signing
          # xcode-project use-profiles
        
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      
      - name: Flutter analyze
        script: |
          flutter analyze
      
      - name: Flutter test
        script: |
          flutter test
        ignore_failure: true
      
      - name: Build iOS (No Code Sign)
        script: |
          flutter build ios --release --no-codesign
      
      - name: Create IPA (Manual)
        script: |
          # Create Payload directory
          mkdir -p Payload
          
          # Copy the .app bundle
          cp -r build/ios/iphoneos/Runner.app Payload/
          
          # Create IPA
          zip -r Chauffly.ipa Payload
          
          # Move to build directory
          mkdir -p build/ios/ipa
          mv Chauffly.ipa build/ios/ipa/
          
          # Clean up
          rm -rf Payload
          
          echo "IPA created at: build/ios/ipa/Chauffly.ipa"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com  # Change this to your email
        notify:
          success: true
          failure: true

  # Alternative workflow with code signing (requires Apple Developer Account)
  ios-release-workflow:
    name: iOS Release Build (Code Signed)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        # Add your code signing credentials in Codemagic UI under Environment variables
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.yourcompany.chauffly"  # Change this
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      
      - name: Fetch signing files
        script: |
          # This requires App Store Connect API key set up in Codemagic
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      
      - name: Set up signing certificate
        script: |
          keychain add-certificates
      
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      
      - name: Flutter build iOS
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com  # Change this
        notify:
          success: true
          failure: true
      
      # Uncomment to publish to App Store Connect
      # app_store_connect:
      #   api_key: $APP_STORE_CONNECT_PRIVATE_KEY
      #   key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
      #   issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      #   submit_to_testflight: true
      #   beta_groups:
      #     - Beta Testers
